wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    session_history: code\_session_history.ipynb
    start_time: 1644966621
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      - 16
      - 17
      4: 3.9.7
      5: 0.12.9
      8:
      - 1
      - 3
      - 5
appliance:
  desc: null
  value: refrigerator1
batch_size:
  desc: null
  value: 150
epochs:
  desc: null
  value: 2000
fc1:
  desc: null
  value: 211
fc2:
  desc: null
  value: 109
hidden_size_1:
  desc: null
  value: 64
hidden_size_2:
  desc: null
  value: 85
in_channels:
  desc: null
  value: 1
kernel_size:
  desc: null
  value: 7
learning_rate:
  desc: null
  value: 0.0003318089969908341
out_channels:
  desc: null
  value: 16
weight_decay:
  desc: null
  value: 0
window_size:
  desc: null
  value: 499
